---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wht94.
--- DateTime: 2023/9/8 16:47
---

-- 1、获取优惠卷id
local voucherId = ARGV[1]
-- 2、获取用户id
local userId = ARGV[2]
-- 2.1、获取订单id
local orderId = ARGV[3]

-- 3、拼接key
local stockKey = ("seckill:stock:") .. voucherId
local orderKey = ("seckill:order:") .. voucherId

-- 4、判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end

-- 5、将库存扣减，添加到订单中
redis.call('incrby', stockKey, -1)
-- 6、添加该用户到集合中
redis.call('sadd', orderKey, userId)
-- 7、添加订单信息到消息队列中
redis.call('xadd', 'stream.orders', '*', 'voucherId', voucherId, 'userId', userId, 'id', orderId)
return 0